use serde::{Deserialize, Serialize};

/// Machine profile: describes the CNC machine's capabilities and G-code dialect.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MachineProfile {
    pub machine: MachineInfo,
    pub post: PostConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MachineInfo {
    /// Machine name.
    pub name: String,

    /// Controller type (determines base G-code dialect).
    #[serde(default)]
    pub controller: Controller,

    /// X-axis travel in project units.
    pub travel_x: f64,

    /// Y-axis travel in project units.
    pub travel_y: f64,

    /// Z-axis travel in project units.
    pub travel_z: f64,

    /// Maximum spindle RPM.
    pub max_rpm: f64,

    /// Minimum spindle RPM.
    #[serde(default = "default_min_rpm")]
    pub min_rpm: f64,

    /// Whether the machine supports automatic tool changing.
    #[serde(default)]
    pub has_atc: bool,
}

fn default_min_rpm() -> f64 {
    100.0
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum Controller {
    /// LinuxCNC / PathPilot (RS274/NGC dialect).
    #[default]
    LinuxCnc,
    /// GRBL (simplified G-code subset).
    Grbl,
    /// Mach3/Mach4.
    Mach,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostConfig {
    /// Whether to include line numbers (N-words).
    #[serde(default)]
    pub line_numbers: bool,

    /// Number of decimal places for coordinates.
    #[serde(default = "default_decimal_places")]
    pub decimal_places: u32,

    /// Safe Z height above workpiece for rapid moves.
    #[serde(default = "default_safe_z")]
    pub safe_z: f64,

    /// Rapid traverse Z height (close to work, above material).
    #[serde(default = "default_rapid_z")]
    pub rapid_z: f64,

    /// G-code to emit at program end.
    #[serde(default = "default_program_end")]
    pub program_end: String,

    /// Optional program number/comment for the header.
    #[serde(default)]
    pub program_header: Option<String>,
}

fn default_decimal_places() -> u32 {
    4
}

fn default_safe_z() -> f64 {
    1.0
}

fn default_rapid_z() -> f64 {
    0.25
}

fn default_program_end() -> String {
    "M30".into()
}

impl MachineProfile {
    /// Load a machine profile from a TOML string.
    pub fn from_toml(toml_str: &str) -> Result<Self, toml::de::Error> {
        toml::from_str(toml_str)
    }

    /// Create the Tormach PCNC 1100 profile.
    pub fn tormach_pcnc1100() -> Self {
        Self {
            machine: MachineInfo {
                name: "Tormach PCNC 1100".into(),
                controller: Controller::LinuxCnc,
                travel_x: 18.0,
                travel_y: 9.5,
                travel_z: 16.25,
                max_rpm: 5140.0,
                min_rpm: 100.0,
                has_atc: false,
            },
            post: PostConfig {
                line_numbers: false,
                decimal_places: 4,
                safe_z: 1.0,
                rapid_z: 0.25,
                program_end: "M30".into(),
                program_header: Some("(Generated by cabinet-maker)".into()),
            },
        }
    }

    /// Carbide3D Shapeoko XXL — GRBL controller.
    pub fn shapeoko_xxl() -> Self {
        Self {
            machine: MachineInfo {
                name: "Shapeoko XXL".into(),
                controller: Controller::Grbl,
                travel_x: 33.0,
                travel_y: 33.0,
                travel_z: 3.0,
                max_rpm: 30000.0,
                min_rpm: 10000.0,
                has_atc: false,
            },
            post: PostConfig {
                line_numbers: false,
                decimal_places: 3,
                safe_z: 0.5,
                rapid_z: 0.1,
                program_end: "M30".into(),
                program_header: Some("(Generated by cabinet-maker)".into()),
            },
        }
    }

    /// Avid CNC 48x96 — Mach3/4 controller.
    pub fn avid_cnc_48x96() -> Self {
        Self {
            machine: MachineInfo {
                name: "Avid CNC 48x96".into(),
                controller: Controller::Mach,
                travel_x: 48.0,
                travel_y: 96.0,
                travel_z: 6.0,
                max_rpm: 24000.0,
                min_rpm: 5000.0,
                has_atc: false,
            },
            post: PostConfig {
                line_numbers: true,
                decimal_places: 4,
                safe_z: 1.0,
                rapid_z: 0.25,
                program_end: "M30".into(),
                program_header: Some("(Generated by cabinet-maker)".into()),
            },
        }
    }
}
